// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sad_react_WebAPI.Models;

#nullable disable

namespace sad_react_WebAPI.Migrations
{
    [DbContext(typeof(BookingDBContext))]
    partial class BookingDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sad_react_WebAPI.Models.EventClient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("endTime")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("eventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("others")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("startTime")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("eventDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("EventClients");
                });
#pragma warning restore 612, 618
        }
    }
}
